### ISSUE TITLE
Missing css in document loaded

### ISSUE THREAD

**Issue by clementbiron** [OpenTermsArchive/contribution-tool#8]
When loading this document `https://www.salto.fr/politique-de-confidentialite/politique-de-traitement-des-donnees-personnelles` it is impossible to make a correct selection because css is missing.

![image](https://user-images.githubusercontent.com/364319/152365959-811f7928-b9ae-4343-aa7b-1941e6210a2c.png)

**Comment by clementbiron** [comment]
Same error for `https://www.laredoute.fr/espace-mentions_legales.aspx`

![image](https://user-images.githubusercontent.com/364319/152957537-d432a288-9be2-40f8-8d6e-780dcec3ed01.png)

**Comment by martinratinaud** [comment]
> https://www.laredoute.fr/espace-mentions_legales.aspx

This is due to styled-components not writing down all specified css
I have done a patch that recreates the styles directly from reading the DOM elements




> Same error for `https://www.laredoute.fr/espace-mentions_legales.aspx`
> 
> ![image](https://user-images.githubusercontent.com/364319/152957537-d432a288-9be2-40f8-8d6e-780dcec3ed01.png)

This was due to the fact that stylesheets are not suffixed by `.css` and thus our integrated server does not manage to handle them correctly.
I've appended it
